// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: s1mme/s1mme.proto

package s1mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cause represents a result of attach / detach.
type Cause int32

const (
	Cause_INVALID        Cause = 0
	Cause_SUCCESS        Cause = 1
	Cause_GW_UNAVAILABLE Cause = 2
)

// Enum value maps for Cause.
var (
	Cause_name = map[int32]string{
		0: "INVALID",
		1: "SUCCESS",
		2: "GW_UNAVAILABLE",
	}
	Cause_value = map[string]int32{
		"INVALID":        0,
		"SUCCESS":        1,
		"GW_UNAVAILABLE": 2,
	}
)

func (x Cause) Enum() *Cause {
	p := new(Cause)
	*p = x
	return p
}

func (x Cause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause) Descriptor() protoreflect.EnumDescriptor {
	return file_s1mme_s1mme_proto_enumTypes[0].Descriptor()
}

func (Cause) Type() protoreflect.EnumType {
	return &file_s1mme_s1mme_proto_enumTypes[0]
}

func (x Cause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause.Descriptor instead.
func (Cause) EnumDescriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{0}
}

type Location_RATType int32

const (
	Location_INVALID        Location_RATType = 0
	Location_UTRAN          Location_RATType = 1
	Location_GERAN          Location_RATType = 2
	Location_WLAN           Location_RATType = 3
	Location_GAN            Location_RATType = 4
	Location_HSPA_EVOLUTION Location_RATType = 5
	Location_EUTRAN         Location_RATType = 6
	Location_VIRTUAL        Location_RATType = 7
	Location_EUTRAN_NB_IOT  Location_RATType = 8
	Location_LTEM           Location_RATType = 9
	Location_NR             Location_RATType = 10
)

// Enum value maps for Location_RATType.
var (
	Location_RATType_name = map[int32]string{
		0:  "INVALID",
		1:  "UTRAN",
		2:  "GERAN",
		3:  "WLAN",
		4:  "GAN",
		5:  "HSPA_EVOLUTION",
		6:  "EUTRAN",
		7:  "VIRTUAL",
		8:  "EUTRAN_NB_IOT",
		9:  "LTEM",
		10: "NR",
	}
	Location_RATType_value = map[string]int32{
		"INVALID":        0,
		"UTRAN":          1,
		"GERAN":          2,
		"WLAN":           3,
		"GAN":            4,
		"HSPA_EVOLUTION": 5,
		"EUTRAN":         6,
		"VIRTUAL":        7,
		"EUTRAN_NB_IOT":  8,
		"LTEM":           9,
		"NR":             10,
	}
)

func (x Location_RATType) Enum() *Location_RATType {
	p := new(Location_RATType)
	*p = x
	return p
}

func (x Location_RATType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Location_RATType) Descriptor() protoreflect.EnumDescriptor {
	return file_s1mme_s1mme_proto_enumTypes[1].Descriptor()
}

func (Location_RATType) Type() protoreflect.EnumType {
	return &file_s1mme_s1mme_proto_enumTypes[1]
}

func (x Location_RATType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Location_RATType.Descriptor instead.
func (Location_RATType) EnumDescriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{2, 0}
}

// AttachRequest is used to request MME to create a session/bearer.
type AttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imsi     string    `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	Msisdn   string    `protobuf:"bytes,2,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	Imeisv   string    `protobuf:"bytes,3,opt,name=imeisv,proto3" json:"imeisv,omitempty"`
	S1UAddr  string    `protobuf:"bytes,4,opt,name=s1u_addr,json=s1uAddr,proto3" json:"s1u_addr,omitempty"`
	SrcIp    string    `protobuf:"bytes,5,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	ITei     uint32    `protobuf:"varint,6,opt,name=i_tei,json=iTei,proto3" json:"i_tei,omitempty"`
	Location *Location `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Reattach bool      `protobuf:"varint,8,opt,name=reattach,proto3" json:"reattach,omitempty"`
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s1mme_s1mme_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s1mme_s1mme_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{0}
}

func (x *AttachRequest) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *AttachRequest) GetMsisdn() string {
	if x != nil {
		return x.Msisdn
	}
	return ""
}

func (x *AttachRequest) GetImeisv() string {
	if x != nil {
		return x.Imeisv
	}
	return ""
}

func (x *AttachRequest) GetS1UAddr() string {
	if x != nil {
		return x.S1UAddr
	}
	return ""
}

func (x *AttachRequest) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *AttachRequest) GetITei() uint32 {
	if x != nil {
		return x.ITei
	}
	return 0
}

func (x *AttachRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AttachRequest) GetReattach() bool {
	if x != nil {
		return x.Reattach
	}
	return false
}

// AttachResponse is used to respond to AttachRequest.
type AttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cause   Cause  `protobuf:"varint,1,opt,name=cause,proto3,enum=s1mme.Cause" json:"cause,omitempty"` // result
	SgwAddr string `protobuf:"bytes,2,opt,name=sgw_addr,json=sgwAddr,proto3" json:"sgw_addr,omitempty"`
	OTei    uint32 `protobuf:"varint,3,opt,name=o_tei,json=oTei,proto3" json:"o_tei,omitempty"`
	SrcIp   string `protobuf:"bytes,4,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s1mme_s1mme_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s1mme_s1mme_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{1}
}

func (x *AttachResponse) GetCause() Cause {
	if x != nil {
		return x.Cause
	}
	return Cause_INVALID
}

func (x *AttachResponse) GetSgwAddr() string {
	if x != nil {
		return x.SgwAddr
	}
	return ""
}

func (x *AttachResponse) GetOTei() uint32 {
	if x != nil {
		return x.OTei
	}
	return 0
}

func (x *AttachResponse) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

// Location represents a set of location-related information.
type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mcc     string           `protobuf:"bytes,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc     string           `protobuf:"bytes,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	RatType Location_RATType `protobuf:"varint,3,opt,name=rat_type,json=ratType,proto3,enum=s1mme.Location_RATType" json:"rat_type,omitempty"`
	Tai     uint32           `protobuf:"varint,4,opt,name=tai,proto3" json:"tai,omitempty"`
	Eci     uint32           `protobuf:"varint,5,opt,name=eci,proto3" json:"eci,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s1mme_s1mme_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_s1mme_s1mme_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *Location) GetMnc() string {
	if x != nil {
		return x.Mnc
	}
	return ""
}

func (x *Location) GetRatType() Location_RATType {
	if x != nil {
		return x.RatType
	}
	return Location_INVALID
}

func (x *Location) GetTai() uint32 {
	if x != nil {
		return x.Tai
	}
	return 0
}

func (x *Location) GetEci() uint32 {
	if x != nil {
		return x.Eci
	}
	return 0
}

// DetachRequest is used to request MME to delete a session/bearer.
type DetachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imsi string `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
}

func (x *DetachRequest) Reset() {
	*x = DetachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s1mme_s1mme_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachRequest) ProtoMessage() {}

func (x *DetachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s1mme_s1mme_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachRequest.ProtoReflect.Descriptor instead.
func (*DetachRequest) Descriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{3}
}

func (x *DetachRequest) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

// DetachResponse is used to respond to DetachRequest.
type DetachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cause Cause `protobuf:"varint,1,opt,name=cause,proto3,enum=s1mme.Cause" json:"cause,omitempty"`
}

func (x *DetachResponse) Reset() {
	*x = DetachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s1mme_s1mme_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachResponse) ProtoMessage() {}

func (x *DetachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s1mme_s1mme_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachResponse.ProtoReflect.Descriptor instead.
func (*DetachResponse) Descriptor() ([]byte, []int) {
	return file_s1mme_s1mme_proto_rawDescGZIP(), []int{4}
}

func (x *DetachResponse) GetCause() Cause {
	if x != nil {
		return x.Cause
	}
	return Cause_INVALID
}

var File_s1mme_s1mme_proto protoreflect.FileDescriptor

var file_s1mme_s1mme_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2f, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x22, 0xe3, 0x01, 0x0a, 0x0d, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x6d, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x73, 0x69,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x65, 0x69,
	0x73, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x65, 0x69, 0x73, 0x76,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x31, 0x75, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x31, 0x75, 0x41, 0x64, 0x64, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x72, 0x63, 0x5f, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x72, 0x63,
	0x49, 0x70, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x5f, 0x74, 0x65, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x69, 0x54, 0x65, 0x69, 0x12, 0x2b, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x31, 0x6d, 0x6d,
	0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x22, 0x7b, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2e, 0x43, 0x61, 0x75, 0x73, 0x65, 0x52,
	0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x67, 0x77, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x67, 0x77, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x13, 0x0a, 0x05, 0x6f, 0x5f, 0x74, 0x65, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x6f, 0x54, 0x65, 0x69, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x70, 0x22, 0x9a, 0x02,
	0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x63,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x63, 0x63, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x6e, 0x63, 0x12, 0x32,
	0x0a, 0x08, 0x72, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x41, 0x54, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x72, 0x61, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x74, 0x61, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x63, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x65, 0x63, 0x69, 0x22, 0x91, 0x01, 0x0a, 0x07, 0x52, 0x41, 0x54, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x55, 0x54, 0x52, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x45,
	0x52, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x4c, 0x41, 0x4e, 0x10, 0x03, 0x12,
	0x07, 0x0a, 0x03, 0x47, 0x41, 0x4e, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x53, 0x50, 0x41,
	0x5f, 0x45, 0x56, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x45, 0x55, 0x54, 0x52, 0x41, 0x4e, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x52, 0x54,
	0x55, 0x41, 0x4c, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x55, 0x54, 0x52, 0x41, 0x4e, 0x5f,
	0x4e, 0x42, 0x5f, 0x49, 0x4f, 0x54, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x54, 0x45, 0x4d,
	0x10, 0x09, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x52, 0x10, 0x0a, 0x22, 0x23, 0x0a, 0x0d, 0x44, 0x65,
	0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6d, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x22,
	0x34, 0x0a, 0x0e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2e, 0x43, 0x61, 0x75, 0x73, 0x65, 0x52, 0x05,
	0x63, 0x61, 0x75, 0x73, 0x65, 0x2a, 0x35, 0x0a, 0x05, 0x43, 0x61, 0x75, 0x73, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x57, 0x5f, 0x55,
	0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x32, 0x7c, 0x0a, 0x08,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x12, 0x14, 0x2e, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x31, 0x6d, 0x6d, 0x65,
	0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x37, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x73, 0x31,
	0x6d, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x73, 0x31, 0x6d, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x73, 0x31, 0x6d, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s1mme_s1mme_proto_rawDescOnce sync.Once
	file_s1mme_s1mme_proto_rawDescData = file_s1mme_s1mme_proto_rawDesc
)

func file_s1mme_s1mme_proto_rawDescGZIP() []byte {
	file_s1mme_s1mme_proto_rawDescOnce.Do(func() {
		file_s1mme_s1mme_proto_rawDescData = protoimpl.X.CompressGZIP(file_s1mme_s1mme_proto_rawDescData)
	})
	return file_s1mme_s1mme_proto_rawDescData
}

var file_s1mme_s1mme_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_s1mme_s1mme_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_s1mme_s1mme_proto_goTypes = []interface{}{
	(Cause)(0),             // 0: s1mme.Cause
	(Location_RATType)(0),  // 1: s1mme.Location.RATType
	(*AttachRequest)(nil),  // 2: s1mme.AttachRequest
	(*AttachResponse)(nil), // 3: s1mme.AttachResponse
	(*Location)(nil),       // 4: s1mme.Location
	(*DetachRequest)(nil),  // 5: s1mme.DetachRequest
	(*DetachResponse)(nil), // 6: s1mme.DetachResponse
}
var file_s1mme_s1mme_proto_depIdxs = []int32{
	4, // 0: s1mme.AttachRequest.location:type_name -> s1mme.Location
	0, // 1: s1mme.AttachResponse.cause:type_name -> s1mme.Cause
	1, // 2: s1mme.Location.rat_type:type_name -> s1mme.Location.RATType
	0, // 3: s1mme.DetachResponse.cause:type_name -> s1mme.Cause
	2, // 4: s1mme.Attacher.Attach:input_type -> s1mme.AttachRequest
	5, // 5: s1mme.Attacher.Detach:input_type -> s1mme.DetachRequest
	3, // 6: s1mme.Attacher.Attach:output_type -> s1mme.AttachResponse
	6, // 7: s1mme.Attacher.Detach:output_type -> s1mme.DetachResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_s1mme_s1mme_proto_init() }
func file_s1mme_s1mme_proto_init() {
	if File_s1mme_s1mme_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s1mme_s1mme_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s1mme_s1mme_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s1mme_s1mme_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s1mme_s1mme_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s1mme_s1mme_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s1mme_s1mme_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s1mme_s1mme_proto_goTypes,
		DependencyIndexes: file_s1mme_s1mme_proto_depIdxs,
		EnumInfos:         file_s1mme_s1mme_proto_enumTypes,
		MessageInfos:      file_s1mme_s1mme_proto_msgTypes,
	}.Build()
	File_s1mme_s1mme_proto = out.File
	file_s1mme_s1mme_proto_rawDesc = nil
	file_s1mme_s1mme_proto_goTypes = nil
	file_s1mme_s1mme_proto_depIdxs = nil
}
